version: '3.4'

services:
  tradingapi:
    build:
      context: .
      dockerfile: TradesApi.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=db;Database=TradingDb;User=sa;Password=SecurePassword123!;Trusted_Connection=False;Encrypt=False;
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - db
      - rabbitmq
    networks:
      - trading-network

  trade-logger:
    build:
      context: .
      dockerfile: TradeLogger.ConsoleApp/Dockerfile
    depends_on:
      - db
      - rabbitmq
    networks:
      - trading-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=SecurePassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - trading-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"   # Management plugin UI
      - "5672:5672"     # AMQP protocol port
    networks:
      - trading-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  trading-network:
    driver: bridge
