version: '3.4'

services:
  tradingapi:
    build:
      context: .
      dockerfile: TradesApi.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=db;Database=TradingDb;User=sa;Password=${DB_PASSWORD};Trusted_Connection=False;Encrypt=False;
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      - db
      - rabbitmq
    networks:
      - trading-network

  trade-logger:
    build:
      context: .
      dockerfile: TradeLogger.ConsoleApp/Dockerfile
    depends_on:
      - db
      - rabbitmq
    networks:
      - trading-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - trading-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"  
    networks:
      - trading-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

networks:
  trading-network:
    driver: bridge
